# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgAddRecordsUI_ru.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgAddRecords(object):
    def setupUi(self, dlgAddRecords):
        dlgAddRecords.setObjectName("dlgAddRecords")
        dlgAddRecords.resize(562, 328)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        dlgAddRecords.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconsOther/Icons/appIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgAddRecords.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(dlgAddRecords)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblName = QtWidgets.QLabel(dlgAddRecords)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout.addWidget(self.lblName)
        self.ledName = QtWidgets.QLineEdit(dlgAddRecords)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ledName.setFont(font)
        self.ledName.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ledName.setObjectName("ledName")
        self.horizontalLayout.addWidget(self.ledName)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblPhoneNumber = QtWidgets.QLabel(dlgAddRecords)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPhoneNumber.setFont(font)
        self.lblPhoneNumber.setObjectName("lblPhoneNumber")
        self.horizontalLayout_2.addWidget(self.lblPhoneNumber)
        self.ledPhoneNumber = QtWidgets.QLineEdit(dlgAddRecords)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ledPhoneNumber.setFont(font)
        self.ledPhoneNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ledPhoneNumber.setObjectName("ledPhoneNumber")
        self.horizontalLayout_2.addWidget(self.ledPhoneNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(dlgAddRecords)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblPhonesForAdd = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPhonesForAdd.setFont(font)
        self.lblPhonesForAdd.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lblPhonesForAdd.setObjectName("lblPhonesForAdd")
        self.verticalLayout_2.addWidget(self.lblPhonesForAdd)
        self.lwdgPhonesForAdd = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lwdgPhonesForAdd.setFont(font)
        self.lwdgPhonesForAdd.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lwdgPhonesForAdd.setStyleSheet("")
        self.lwdgPhonesForAdd.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lwdgPhonesForAdd.setObjectName("lwdgPhonesForAdd")
        self.verticalLayout_2.addWidget(self.lwdgPhonesForAdd)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.btnAddNumberToList = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAddNumberToList.setFont(font)
        self.btnAddNumberToList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconsC9d/Icons/C9d/user_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddNumberToList.setIcon(icon1)
        self.btnAddNumberToList.setIconSize(QtCore.QSize(32, 32))
        self.btnAddNumberToList.setObjectName("btnAddNumberToList")
        self.verticalLayout.addWidget(self.btnAddNumberToList)
        self.btnDelNumberFromList = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDelNumberFromList.setFont(font)
        self.btnDelNumberFromList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconsOneBit/Icons/OneBit/onebit_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelNumberFromList.setIcon(icon2)
        self.btnDelNumberFromList.setIconSize(QtCore.QSize(32, 32))
        self.btnDelNumberFromList.setObjectName("btnDelNumberFromList")
        self.verticalLayout.addWidget(self.btnDelNumberFromList)
        self.btnFinishAndSave = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnFinishAndSave.setFont(font)
        self.btnFinishAndSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconsBasic/Icons/BasicSet/save_64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFinishAndSave.setIcon(icon3)
        self.btnFinishAndSave.setIconSize(QtCore.QSize(32, 32))
        self.btnFinishAndSave.setObjectName("btnFinishAndSave")
        self.verticalLayout.addWidget(self.btnFinishAndSave)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancel.setFont(font)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconsBasic/Icons/BasicSet/block_64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon4)
        self.btnCancel.setIconSize(QtCore.QSize(32, 32))
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout.addWidget(self.btnCancel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(dlgAddRecords)
        QtCore.QMetaObject.connectSlotsByName(dlgAddRecords)
        dlgAddRecords.setTabOrder(self.ledName, self.ledPhoneNumber)
        dlgAddRecords.setTabOrder(self.ledPhoneNumber, self.btnAddNumberToList)
        dlgAddRecords.setTabOrder(self.btnAddNumberToList, self.btnDelNumberFromList)
        dlgAddRecords.setTabOrder(self.btnDelNumberFromList, self.btnFinishAndSave)
        dlgAddRecords.setTabOrder(self.btnFinishAndSave, self.btnCancel)
        dlgAddRecords.setTabOrder(self.btnCancel, self.lwdgPhonesForAdd)

    def retranslateUi(self, dlgAddRecords):
        _translate = QtCore.QCoreApplication.translate
        dlgAddRecords.setWindowTitle(_translate("dlgAddRecords", "Добавление записи"))
        self.lblName.setText(_translate("dlgAddRecords", "Имя: "))
        self.lblPhoneNumber.setText(_translate("dlgAddRecords", "Номер телефона: "))
        self.lblPhonesForAdd.setText(_translate("dlgAddRecords", "Список добавляемых номеров:"))
        self.btnAddNumberToList.setText(_translate("dlgAddRecords", " Добавить\n"
"  номер"))
        self.btnDelNumberFromList.setText(_translate("dlgAddRecords", "     Удалить\n"
" выбранные номера"))
        self.btnFinishAndSave.setText(_translate("dlgAddRecords", "  Закончить\n"
" и сохранить"))
        self.btnCancel.setText(_translate("dlgAddRecords", " Отмена\n"
" (Выход)"))

import res_rc
