# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgEditRecordUI_ru.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgEditRecord(object):
    def setupUi(self, dlgEditRecord):
        dlgEditRecord.setObjectName("dlgEditRecord")
        dlgEditRecord.resize(562, 337)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        dlgEditRecord.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconsOther/Icons/appIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgEditRecord.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(dlgEditRecord)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblName = QtWidgets.QLabel(dlgEditRecord)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout.addWidget(self.lblName)
        self.ledName = QtWidgets.QLineEdit(dlgEditRecord)
        self.ledName.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ledName.setObjectName("ledName")
        self.horizontalLayout.addWidget(self.ledName)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblPhoneNumber = QtWidgets.QLabel(dlgEditRecord)
        self.lblPhoneNumber.setObjectName("lblPhoneNumber")
        self.horizontalLayout_2.addWidget(self.lblPhoneNumber)
        self.ledPhoneNumber = QtWidgets.QLineEdit(dlgEditRecord)
        self.ledPhoneNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ledPhoneNumber.setObjectName("ledPhoneNumber")
        self.horizontalLayout_2.addWidget(self.ledPhoneNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(dlgEditRecord)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblPhonesForAdd = QtWidgets.QLabel(self.layoutWidget)
        self.lblPhonesForAdd.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lblPhonesForAdd.setObjectName("lblPhonesForAdd")
        self.verticalLayout_2.addWidget(self.lblPhonesForAdd)
        self.lwdgPhonesForEdit = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lwdgPhonesForEdit.setFont(font)
        self.lwdgPhonesForEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lwdgPhonesForEdit.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lwdgPhonesForEdit.setObjectName("lwdgPhonesForEdit")
        self.verticalLayout_2.addWidget(self.lwdgPhonesForEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.btnAddNumberToList = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAddNumberToList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconsC9d/Icons/C9d/user_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddNumberToList.setIcon(icon1)
        self.btnAddNumberToList.setIconSize(QtCore.QSize(32, 32))
        self.btnAddNumberToList.setObjectName("btnAddNumberToList")
        self.verticalLayout.addWidget(self.btnAddNumberToList)
        self.btnDelSelectedNumbers = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnDelSelectedNumbers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconsOneBit/Icons/OneBit/onebit_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelSelectedNumbers.setIcon(icon2)
        self.btnDelSelectedNumbers.setIconSize(QtCore.QSize(32, 32))
        self.btnDelSelectedNumbers.setObjectName("btnDelSelectedNumbers")
        self.verticalLayout.addWidget(self.btnDelSelectedNumbers)
        self.btnFinishAndSave = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnFinishAndSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconsBasic/Icons/BasicSet/save_64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFinishAndSave.setIcon(icon3)
        self.btnFinishAndSave.setIconSize(QtCore.QSize(32, 32))
        self.btnFinishAndSave.setObjectName("btnFinishAndSave")
        self.verticalLayout.addWidget(self.btnFinishAndSave)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconsBasic/Icons/BasicSet/block_64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon4)
        self.btnCancel.setIconSize(QtCore.QSize(32, 32))
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout.addWidget(self.btnCancel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(dlgEditRecord)
        QtCore.QMetaObject.connectSlotsByName(dlgEditRecord)
        dlgEditRecord.setTabOrder(self.ledName, self.ledPhoneNumber)
        dlgEditRecord.setTabOrder(self.ledPhoneNumber, self.btnAddNumberToList)
        dlgEditRecord.setTabOrder(self.btnAddNumberToList, self.btnDelSelectedNumbers)
        dlgEditRecord.setTabOrder(self.btnDelSelectedNumbers, self.btnFinishAndSave)
        dlgEditRecord.setTabOrder(self.btnFinishAndSave, self.btnCancel)
        dlgEditRecord.setTabOrder(self.btnCancel, self.lwdgPhonesForEdit)

    def retranslateUi(self, dlgEditRecord):
        _translate = QtCore.QCoreApplication.translate
        dlgEditRecord.setWindowTitle(_translate("dlgEditRecord", "Редактирование записи"))
        self.lblName.setText(_translate("dlgEditRecord", "Имя: "))
        self.lblPhoneNumber.setText(_translate("dlgEditRecord", "Номер телефона: "))
        self.lblPhonesForAdd.setText(_translate("dlgEditRecord", "Список телефонных номеров:"))
        self.btnAddNumberToList.setText(_translate("dlgEditRecord", " Добавить\n"
"  номер"))
        self.btnDelSelectedNumbers.setText(_translate("dlgEditRecord", "     Удалить\n"
" выбранные номера"))
        self.btnFinishAndSave.setText(_translate("dlgEditRecord", "  Закончить\n"
" и сохранить"))
        self.btnCancel.setText(_translate("dlgEditRecord", " Отмена\n"
" (Выход)"))

import res_rc
