# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fMainUI_ru.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fMain(object):
    def setupUi(self, fMain):
        fMain.setObjectName("fMain")
        fMain.resize(1050, 511)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        fMain.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconsOther/Icons/appIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        fMain.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(fMain)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setBold(False)
        font.setWeight(50)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lwdgOutput = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwdgOutput.sizePolicy().hasHeightForWidth())
        self.lwdgOutput.setSizePolicy(sizePolicy)
        self.lwdgOutput.setMinimumSize(QtCore.QSize(0, 0))
        self.lwdgOutput.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lwdgOutput.setFont(font)
        self.lwdgOutput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lwdgOutput.setMouseTracking(False)
        self.lwdgOutput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lwdgOutput.setStyleSheet("")
        self.lwdgOutput.setAlternatingRowColors(True)
        self.lwdgOutput.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lwdgOutput.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.lwdgOutput.setMovement(QtWidgets.QListView.Static)
        self.lwdgOutput.setSelectionRectVisible(True)
        self.lwdgOutput.setObjectName("lwdgOutput")
        self.verticalLayout_2.addWidget(self.lwdgOutput)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lblZoomIn = QtWidgets.QLabel(self.layoutWidget)
        self.lblZoomIn.setMaximumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setBold(False)
        font.setWeight(50)
        self.lblZoomIn.setFont(font)
        self.lblZoomIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblZoomIn.setText("")
        self.lblZoomIn.setPixmap(QtGui.QPixmap(":/iconsC9d/Icons/C9d/zoom_in.png"))
        self.lblZoomIn.setScaledContents(True)
        self.lblZoomIn.setWordWrap(False)
        self.lblZoomIn.setObjectName("lblZoomIn")
        self.horizontalLayout_2.addWidget(self.lblZoomIn)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lblZoomOut = QtWidgets.QLabel(self.layoutWidget)
        self.lblZoomOut.setMaximumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setBold(False)
        font.setWeight(50)
        self.lblZoomOut.setFont(font)
        self.lblZoomOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblZoomOut.setText("")
        self.lblZoomOut.setPixmap(QtGui.QPixmap(":/iconsC9d/Icons/C9d/zoom_out.png"))
        self.lblZoomOut.setScaledContents(True)
        self.lblZoomOut.setWordWrap(False)
        self.lblZoomOut.setObjectName("lblZoomOut")
        self.horizontalLayout_2.addWidget(self.lblZoomOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSearch = QtWidgets.QLabel(self.layoutWidget)
        self.lblSearch.setMaximumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblSearch.setFont(font)
        self.lblSearch.setText("")
        self.lblSearch.setPixmap(QtGui.QPixmap(":/iconsBasic/Icons/BasicSet/search_64.png"))
        self.lblSearch.setScaledContents(True)
        self.lblSearch.setObjectName("lblSearch")
        self.horizontalLayout.addWidget(self.lblSearch)
        self.ledSearch = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.ledSearch.setFont(font)
        self.ledSearch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ledSearch.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ledSearch.setObjectName("ledSearch")
        self.horizontalLayout.addWidget(self.ledSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbxLanguage = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxLanguage.sizePolicy().hasHeightForWidth())
        self.cbxLanguage.setSizePolicy(sizePolicy)
        self.cbxLanguage.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cbxLanguage.setFont(font)
        self.cbxLanguage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbxLanguage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxLanguage.setIconSize(QtCore.QSize(24, 24))
        self.cbxLanguage.setObjectName("cbxLanguage")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconsFlags/Icons/Flags/ru_round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbxLanguage.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconsFlags/Icons/Flags/us_round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbxLanguage.addItem(icon2, "")
        self.verticalLayout.addWidget(self.cbxLanguage)
        self.btnAddRecords = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddRecords.sizePolicy().hasHeightForWidth())
        self.btnAddRecords.setSizePolicy(sizePolicy)
        self.btnAddRecords.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnAddRecords.setFont(font)
        self.btnAddRecords.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconsC9d/Icons/C9d/group_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddRecords.setIcon(icon3)
        self.btnAddRecords.setIconSize(QtCore.QSize(32, 32))
        self.btnAddRecords.setObjectName("btnAddRecords")
        self.verticalLayout.addWidget(self.btnAddRecords)
        self.btnDelSelectedRecords = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelSelectedRecords.sizePolicy().hasHeightForWidth())
        self.btnDelSelectedRecords.setSizePolicy(sizePolicy)
        self.btnDelSelectedRecords.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnDelSelectedRecords.setFont(font)
        self.btnDelSelectedRecords.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconsC9d/Icons/C9d/group_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelSelectedRecords.setIcon(icon4)
        self.btnDelSelectedRecords.setIconSize(QtCore.QSize(32, 32))
        self.btnDelSelectedRecords.setObjectName("btnDelSelectedRecords")
        self.verticalLayout.addWidget(self.btnDelSelectedRecords)
        self.btnEditRecord = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditRecord.sizePolicy().hasHeightForWidth())
        self.btnEditRecord.setSizePolicy(sizePolicy)
        self.btnEditRecord.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnEditRecord.setFont(font)
        self.btnEditRecord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconsOneBit/Icons/OneBit/onebit_20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditRecord.setIcon(icon5)
        self.btnEditRecord.setIconSize(QtCore.QSize(32, 32))
        self.btnEditRecord.setObjectName("btnEditRecord")
        self.verticalLayout.addWidget(self.btnEditRecord)
        self.btnShowAllRecords = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowAllRecords.sizePolicy().hasHeightForWidth())
        self.btnShowAllRecords.setSizePolicy(sizePolicy)
        self.btnShowAllRecords.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnShowAllRecords.setFont(font)
        self.btnShowAllRecords.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconsC9d/Icons/C9d/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShowAllRecords.setIcon(icon6)
        self.btnShowAllRecords.setIconSize(QtCore.QSize(32, 32))
        self.btnShowAllRecords.setObjectName("btnShowAllRecords")
        self.verticalLayout.addWidget(self.btnShowAllRecords)
        self.btnCleanAll = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCleanAll.sizePolicy().hasHeightForWidth())
        self.btnCleanAll.setSizePolicy(sizePolicy)
        self.btnCleanAll.setBaseSize(QtCore.QSize(150, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 234, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnCleanAll.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnCleanAll.setFont(font)
        self.btnCleanAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCleanAll.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(242, 234, 14);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconsOneBit/Icons/OneBit/onebit_49.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCleanAll.setIcon(icon7)
        self.btnCleanAll.setIconSize(QtCore.QSize(32, 32))
        self.btnCleanAll.setObjectName("btnCleanAll")
        self.verticalLayout.addWidget(self.btnCleanAll)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btnExit = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnExit.setFont(font)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/iconsOneBit/Icons/OneBit/onebit_33.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon8)
        self.btnExit.setIconSize(QtCore.QSize(32, 32))
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout.addWidget(self.btnExit)
        self.verticalLayout_3.addWidget(self.splitter)
        self.lblFoundRecords = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblFoundRecords.setFont(font)
        self.lblFoundRecords.setObjectName("lblFoundRecords")
        self.verticalLayout_3.addWidget(self.lblFoundRecords)
        self.lblSelectedRecords = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblSelectedRecords.setFont(font)
        self.lblSelectedRecords.setObjectName("lblSelectedRecords")
        self.verticalLayout_3.addWidget(self.lblSelectedRecords)
        self.lblTotalRecords = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblTotalRecords.setFont(font)
        self.lblTotalRecords.setObjectName("lblTotalRecords")
        self.verticalLayout_3.addWidget(self.lblTotalRecords)
        self.splitter.raise_()
        self.lblSelectedRecords.raise_()
        self.lblFoundRecords.raise_()
        self.lblTotalRecords.raise_()
        fMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(fMain)
        self.statusbar.setObjectName("statusbar")
        fMain.setStatusBar(self.statusbar)

        self.retranslateUi(fMain)
        self.cbxLanguage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fMain)

    def retranslateUi(self, fMain):
        _translate = QtCore.QCoreApplication.translate
        fMain.setWindowTitle(_translate("fMain", "Телефонный справочник"))
        self.lblZoomIn.setToolTip(_translate("fMain", "<html><head/><body><p><span style=\" font-size:12pt;\">Увеличить</span></p></body></html>"))
        self.lblZoomOut.setToolTip(_translate("fMain", "<html><head/><body><p><span style=\" font-size:12pt;\">Уменьшить</span></p></body></html>"))
        self.ledSearch.setText(_translate("fMain", "Поиск..."))
        self.cbxLanguage.setItemText(0, _translate("fMain", " Русский"))
        self.cbxLanguage.setItemText(1, _translate("fMain", " English"))
        self.btnAddRecords.setText(_translate("fMain", " Добавить\n"
"  записи"))
        self.btnDelSelectedRecords.setText(_translate("fMain", "     Удалить\n"
" выбранные записи"))
        self.btnEditRecord.setText(_translate("fMain", " Редактировать\n"
"    запись"))
        self.btnShowAllRecords.setText(_translate("fMain", "     Вывести\n"
" весь справочник"))
        self.btnCleanAll.setText(_translate("fMain", "   Удалить\n"
" ВСЕ записи"))
        self.btnExit.setText(_translate("fMain", " Выход"))
        self.lblFoundRecords.setText(_translate("fMain", " Найдено: "))
        self.lblSelectedRecords.setText(_translate("fMain", " Выбрано: "))
        self.lblTotalRecords.setText(_translate("fMain", " Количество записей в словаре: "))

import res_rc
